#!/bin/sh

##------ Bspwm ------##

# Window settings and workspaces
bspc monitor -d I II III IV V

bspc config border_width         2
bspc config window_gap           4
bspc config split_ratio          0.50

bspc config borderless_monocle   	true
bspc config gapless_monocle      	true
bspc config single_monocle 	 	false
bspc config paddingless_monocle  	true
bspc config focus_follows_pointer	true

# Source the colors from pywal
. "${HOME}/.cache/wal/colors.sh"

# Border colors
bspc config focused_border_color	"$color2"
bspc config normal_border_color         "$color1"

##------- Workspaces ------##

# Kill all existing rules first before restarting
bspc rule -r *:*

# Workspace 1 > Terminal
bspc rule -a Alacritty desktop='^1' follow=on focus=on

# Workspace 2 > Internet browser
bspc rule -a firefox desktop='^2' follow=on focus=on

# Workspace 3 > File manager, torrent client, etc.
bspc rule -a qBittorent desktop='^3' follow=on focus=on
bspc rule -a Dolphin desktop='^3' follow=on focus=on

# Workspace 4 > Media
bspc rule -a obs desktop='^4' state=floating follow=on focus=on
bspc rule -a mpv desktop='^4' follow=on focus=on
bspc rule -a feh desktop='^4' follow=on focus=on
bspc rule -a Emacs desktop='^4' state=tiled follow=on focus=on

# Workspace 5 > Communications
bspc rule -a discord desktop='^5' follow=on focus=on
bspc rule -a Thunderbird desktop='^5' follow=on focus=on
bspc rule -a teams desktop='^5' follow=on focus=on
bspc rule -a telegram desktop='^5' follow=on focus=on

##------ Essential startup apps ------## 

# Kill existing apps before restarting bspwm
pkill xfce-polkit
pkill ksuperkey
pkill dunst
pkill wal

# Fix cursors in WM
xsetroot -cursor_name left_ptr &

# Launch policy kit agent
/usr/libexec/xfce-polkit &

# Launch pipewire
pipewire &

# Launch keybindings daemon
sh ~/.config/sxhkd/launch.sh &

# Enable Super Key as menu key
ksuperkey -e 'Super_L=Alt_L|F1' &
ksuperkey -e 'Super_R=Alt_L|F1' &

# Launch compositor
sh ~/.config/picom/launch.sh &

# Start polybar
sh ~/.config/polybar/launch.sh &

# Restore wallpaper and dunst colorscheme
wal -i ~/Pictures/wallpapers/girl-red.png -o ~/.config/dunst/launchdunst.sh && wal -R &

# Launch notification daemon
sh ~/.config/dunst/launch.sh &

# Connect wireless headphone
sh ~/.config/bspwm/scripts/wireless-headphone.sh &

##------ EOF ------##
